# -*- coding: utf-8 -*-
"""Dataset nyc crimini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yz-CpQbRpnFpZMHB1dx1nIimAvnJWNPL
"""

import pandas as pd
import requests
import time

def download_crimes_by_year(year, limit=50000, max_offset=800000):
    """
    Downloads NYC crime data for a specific year using the Socrata API.
    Automatically saves the result as a CSV file with the original Italian filename format.
    """
    base_url = "https://data.cityofnewyork.us/resource/qgea-i56i.json"
    results = []
    offset = 0

    while True:
        print(f"Downloading: {year} — offset {offset}")
        query = {
            "$limit": limit,
            "$offset": offset,
            "$where": f"date_extract_y(cmplnt_fr_dt) = {year}"
        }

        r = requests.get(base_url, params=query)
        data = r.json()

        if not data:
            break

        results.extend(data)
        offset += limit
        time.sleep(0.2)  # avoid overloading the API

        if offset >= max_offset:
            print("Maximum offset reached. Forcing stop.")
            break

    df = pd.DataFrame(results)
    df.to_csv(f"nypd_crimini_{year}.csv", index=False)
    print(f"✅ Saved: nypd_crimini_{year}.csv — {len(df)} rows")

# Download data from 2008 to 2012
for year in range(2008, 2013):
    download_crimes_by_year(year)